# Generated by Django 2.2.7 on 2019-11-12 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collaborators',
            field=models.ManyToManyField(related_name='_user_collaborators_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='api.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nextcloud_app_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default=None, max_length=64, null=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='nextcloud_scan_directory',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nextcloud_server_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nextcloud_username',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='scan_directory',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
    ]
